#!/bin/bash

. library

if [ $# -ne 1 ]; then
	echo "Usage: $0 command" >&2
	exit 1
fi

check_cmd "$1"

case $? in
0) echo "'$1' found in \$PATH" ;;
1) echo "'$1' not found in \$PATH OR is not executable" ;;
2) echo "'$1' not found in \$PATH" ;;
esac

exit 0
